// Automatically generated by flapigen
package io.github.givimad.rustpotter_java;

/**
 * Supported endianness modes
 */
public enum Endianness {
    LITTLE(0),
    BIG(1),
    NATIVE(2);

    private final int value;
    Endianness(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static Endianness fromInt(int x) {
        switch (x) {
            case 0: return LITTLE;
            case 1: return BIG;
            case 2: return NATIVE;
            default: throw new Error("Invalid value for enum Endianness: " + x);
        }
    }
}
