// Automatically generated by flapigen
package io.github.givimad.rustpotter_java;

/**
 * Dificulty for considering a frame as noise.
 */
public enum NoiseDetectionMode {
    EASIEST(0),
    EASY(1),
    NORMAL(2),
    HARD(3),
    HARDEST(4);

    private final int value;
    NoiseDetectionMode(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static NoiseDetectionMode fromInt(int x) {
        switch (x) {
            case 0: return EASIEST;
            case 1: return EASY;
            case 2: return NORMAL;
            case 3: return HARD;
            case 4: return HARDEST;
            default: throw new Error("Invalid value for enum NoiseDetectionMode: " + x);
        }
    }
}
