// Automatically generated by flapigen
package io.github.givimad.rustpotter_java;


public enum NoiseDetectionMode {
    EASYEST(0),
    EASY(1),
    NORMAL(2),
    HIGH(3),
    HIGHEST(4);

    private final int value;
    NoiseDetectionMode(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static NoiseDetectionMode fromInt(int x) {
        switch (x) {
            case 0: return EASYEST;
            case 1: return EASY;
            case 2: return NORMAL;
            case 3: return HIGH;
            case 4: return HIGHEST;
            default: throw new Error("Invalid value for enum NoiseDetectionMode: " + x);
        }
    }
}
