// Automatically generated by flapigen
package io.github.givimad.rustpotter_java;


public enum SampleFormat {
    INT(0),
    FLOAT(1);

    private final int value;
    SampleFormat(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static SampleFormat fromInt(int x) {
        switch (x) {
            case 0: return INT;
            case 1: return FLOAT;
            default: throw new Error("Invalid value for enum SampleFormat: " + x);
        }
    }
}
