// Automatically generated by flapigen
package io.github.givimad.rustpotter_java;

/**
 * Allowed vad modes.
 */
public enum VadMode {
    QUALITY(0),
    LOW_BITRATE(1),
    AGGRESSIVE(2),
    VERY_AGGRESSIVE(3);

    private final int value;
    VadMode(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static VadMode fromInt(int x) {
        switch (x) {
            case 0: return QUALITY;
            case 1: return LOW_BITRATE;
            case 2: return AGGRESSIVE;
            case 3: return VERY_AGGRESSIVE;
            default: throw new Error("Invalid value for enum VadMode: " + x);
        }
    }
}
